# Generated by Django 4.2.1 on 2023-05-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(default=None, upload_to='pictures/uni.jpg')),
                ('published_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('tech', 'tech'), ('sports', 'sports'), ('news', 'news'), ('education', 'education')], default=None, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=200)),
                ('slug', models.SlugField(default=None)),
            ],
        ),
    ]
